# Generated by Django 5.0.7 on 2024-07-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_storagecapacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='max_capacity',
            field=models.IntegerField(default=100),
        ),
    ]
