# Generated by Django 5.0.7 on 2024-07-11 01:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='condition',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado'), ('Reparado', 'Reparado')], default='Nuevo', max_length=50),
        ),
        migrations.AddField(
            model_name='material',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='material',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
