# Generated by Django 5.0.7 on 2024-07-11 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': [('can_analyze_inventory', 'Can analyze inventory'), ('can_view_reports', 'Can view reports')]},
        ),
    ]
