# Generated by Django 5.0.7 on 2024-07-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('can_manage_storage', 'Can manage storage'), ('can_add_location', 'Can add location'), ('can_edit_location', 'Can edit location'), ('can_delete_location', 'Can delete location')]},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'permissions': [('can_analyze_inventory', 'Can analyze inventory'), ('can_view_reports', 'Can view reports'), ('can_add_material', 'Can add material'), ('can_edit_material', 'Can edit material'), ('can_delete_material', 'Can delete material'), ('can_view_material', 'Can view material')]},
        ),
    ]
