# Generated by Django 5.0.7 on 2024-07-11 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_location_options_alter_material_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'permissions': [('can_manage_storage', 'Can manage storage'), ('can_access_almacenero', 'Can access almacenero view'), ('can_access_responsable_almacen', 'Can access responsable almacen view'), ('can_access_analista_inventario', 'Can access analista inventario view'), ('can_access_gerente', 'Can access gerente view'), ('can_access_gerente_inventario', 'Can access gerente inventario view')]},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={},
        ),
    ]
